[containers]
cgroups = "enabled"
cgroupns = "host"
default_sysctls = []
log_driver = "k8s-file"
pids_limit = 65536
volumes = ["/proc:/proc"]
utsns = "host"
netns = "bridge"

[engine]
cgroup_manager = "cgroupfs"

[network]
network_backend = "netavark"
default_rootless_network_cmd = "pasta"
