import pytest

from tests.conftest import run_in_devbox


@pytest.mark.container
@pytest.mark.parametrize(
    "plugin_path",
    (
        "/sandbox/.config/opencode/plugins/tokenjuice.js",
        "/usr/local/share/tokenjuice/opencode.js",
    ),
)
def test_tokenjuice_opencode_plugin_installed(devbox_image: str, plugin_path: str):
    res = run_in_devbox(
        devbox_image,
        ["cat", plugin_path],
        user="sandbox",
    )
    assert res.returncode == 0, (
        f"tokenjuice OpenCode plugin missing at {plugin_path}.\n"
        f"Stdout: {res.stdout}\nStderr: {res.stderr}"
    )
    assert "generated by tokenjuice" in res.stdout
    assert "createTokenjuiceOpenCodeExtension" in res.stdout


@pytest.mark.container
def test_tokenjuice_doctor_opencode_reports_ok(devbox_image: str):
    res = run_in_devbox(
        devbox_image,
        ["tokenjuice", "doctor", "opencode"],
        user="sandbox",
    )
    assert res.returncode == 0, (
        f"'tokenjuice doctor opencode' failed.\nStdout: {res.stdout}\n"
        f"Stderr: {res.stderr}"
    )
    assert "health: ok" in res.stdout


@pytest.mark.container
def test_ripwire_skills_are_staged_and_active(devbox_image: str):
    for skill_path in (
        "/usr/local/share/ripwire/skills/ripwire-orient/SKILL.md",
        "/sandbox/.agents/skills/ripwire-orient/SKILL.md",
    ):
        res = run_in_devbox(
            devbox_image,
            ["test", "-f", skill_path],
            user="sandbox",
        )
        assert res.returncode == 0, (
            f"Ripwire skill missing at {skill_path}.\n"
            f"Stdout: {res.stdout}\nStderr: {res.stderr}"
        )
