import pytest

from tests.conftest import run_in_devbox


@pytest.mark.container
def test_tokenjuice_opencode_plugin_installed(devbox_image: str):
    plugin_path = "/sandbox/.config/opencode/plugins/tokenjuice.js"
    res = run_in_devbox(
        devbox_image,
        ["cat", plugin_path],
        user="sandbox",
    )
    assert res.returncode == 0, (
        f"tokenjuice OpenCode plugin missing at {plugin_path}.\n"
        f"Stdout: {res.stdout}\nStderr: {res.stderr}"
    )
    assert "generated by tokenjuice" in res.stdout
    assert "createTokenjuiceOpenCodeExtension" in res.stdout


@pytest.mark.container
def test_tokenjuice_doctor_opencode_reports_ok(devbox_image: str):
    res = run_in_devbox(
        devbox_image,
        ["tokenjuice", "doctor", "opencode"],
        user="sandbox",
    )
    assert res.returncode == 0, (
        f"'tokenjuice doctor opencode' failed.\nStdout: {res.stdout}\n"
        f"Stderr: {res.stderr}"
    )
    assert "health: ok" in res.stdout
